---
# The playbook level
- name: Setting up metataxonx in catalog
  hosts: localhost
  gather_facts: false
  become: true

  # The tasks level. Just a yaml list of Ansible "module" objects
  tasks:
    - name: Ensure .bashrc exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.bashrc"
        state: touch

    - name: Add metataxonx alias using playbook directory
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "alias metataxonx='sudo nextflow run {{ ansible_playbook_dir }}/main.nf'"
        create: true
        backup: true