---
# The playbook level
- name: Setting up metataxonx in catalog
  hosts: localhost
  gather_facts: false
  become: true

  # The tasks level. Just a yaml list of Ansible "module" objects
  tasks:
    - name: Make metataxonx executable
      ansible.builtin.copy:
        dest: /usr/local/bin/metataxonx
        mode: "0755"
        content: |
          #!/usr/bin/env bash
          cd "{{ playbook_dir }}"
          exec sudo nextflow run main.nf "$@"